[flavor]
dark = "dracula"

[[icon.prepend_conds]]
if = "dir"
text = "󰉋"

[mgr]
border_symbol = " "

[mgr.border_style]
fg = "#44475a"

[status]
sep_close = ""
sep_open = ""

[tab.sep_close]
close = ""
open = ""

[tab.sep_open]
close = ""
open = ""
