[mgr]
linemode = "none"
ratio = [1, 2, 4]
scrolloff = 5
show_hidden = false
show_symlink = true
sort_by = "natural"
sort_dir_first = true

[[opener.emacs]]
block = true
run = "emacsclient -c -nw \"$@\""

[preview]
max_height = 8000
max_width = 6000
tab_size = 4
wrap = "no"
