# home/modules/email.nix
#
# Proton-only mail via Proton Bridge.
#   sync : isync (mbsync) <-> Bridge on 127.0.0.1
#   send : msmtp        -> Bridge on 127.0.0.1
#   index: mu  (mu4e reads it in Emacs; mu4e.el ships inside pkgs.mu)
#
# Bridge must be running. Host/ports/password are shown in the Bridge GUI;
# the TLS cert is exported from Bridge (Settings -> Export TLS certificates).

{ config, lib, pkgs, ... }:

let
  bridgeCert = "${config.home.homeDirectory}/.config/protonmail/bridge/cert.pem";
  mu4e-pkg = pkgs.emacsPackages.mu4e;
in
{
  accounts.email = {
    maildirBasePath = "Mail";                       # -> ~/Mail
    accounts.proton = {
      primary  = true;
      realName = "Vytautas";
      address  = "wtz@protonmail.ch";
      userName = "wtz@protonmail.ch";

      # ─── PASSWORD ─────────────────────────────────────────────────────────
      # Bridge password (NOT your Proton login), read from Keychain. Add it
      # once with:
      #   security add-generic-password -s proton-bridge -a vp@paulaus.com -w '<bridge-password>' -U
      passwordCommand = "security find-generic-password -s proton-bridge -a vp@paulaus.com -w";

      imap = {
        host = "127.0.0.1"; port = 1143;
        tls = { enable = true; useStartTls = true; certificatesFile = bridgeCert; };
      };
      smtp = {
        host = "127.0.0.1"; port = 1025;
        tls = { enable = true; useStartTls = true; certificatesFile = bridgeCert; };
      };

      mbsync = { enable = true; create = "both"; expunge = "both"; patterns = [ "*" ]; };
      msmtp.enable = true;
    };
  };

  programs.mbsync.enable = true;
  programs.msmtp.enable  = true;

  home.packages = [ 
    pkgs.mu
    mu4e-pkg
  ];

  # Background sync every 5 min. This only runs mbsync, not `mu index` - keeping
  # the maildir fresh on disk; mu4e re-indexes when you update it (`U`). They're
  # split deliberately so a background run never fights mu4e's open mu server.
  launchd.agents.mbsync = {
    enable = true;
    config = {
      ProgramArguments  = [ "${pkgs.isync}/bin/mbsync" "-a" ];
      StartInterval     = 300;
      RunAtLoad         = false;
      EnvironmentVariables.PATH = "/usr/bin:/bin";
      StandardOutPath   = "${config.home.homeDirectory}/.local/state/mbsync/out.log";
      StandardErrorPath = "${config.home.homeDirectory}/.local/state/mbsync/err.log";
    };
  };

  home.activation.mailDirs = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    $DRY_RUN_CMD mkdir -p "${config.home.homeDirectory}/.local/state/mbsync"
  '';

home.file.".emacs.d/nix-mu4e.el".text = ''
    ;; Auto-generated by Home Manager. Do not edit.
    (let* ((pkg-dir "${mu4e-pkg}/share/emacs/site-lisp")
           (elpa-dir (car (file-expand-wildcards (expand-file-name "elpa/mu4e-*" pkg-dir)))))
      (if elpa-dir
          (add-to-list 'load-path elpa-dir)
        (add-to-list 'load-path pkg-dir)))
  '';
}
