theme = "dracula-clear"

[editor]
auto-completion = true
auto-format = true
auto-save = true
bufferline = "always"
color-modes = true
completion-trigger-len = 1
cursorline = true
line-number = "relative"
mouse = true
shell = ["bash", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.gutters]
layout = ["diff", "diagnostics", "spacer"]

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.soft-wrap]
enable = true
max-indent-retain = 0
max-wrap = 25
wrap-indicator = ""

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner", "position", "position-percentage"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "|"

[editor.statusline.mode]
insert = "INS"
normal = "NOR"
select = "SEL"

[keys.normal]
"C-/" = ["toggle_comments"]
C-h = "goto_previous_buffer"
C-i = "goto_next_buffer"
C-x = ":buffer-close"
E = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
G = "goto_last_line"
J = "move_next_long_word_end"
K = "search_prev"
L = "insert_at_line_start"
N = ["extend_to_line_bounds", "delete_selection", "paste_after"]
O = "open_above"
a = ["append_mode", "collapse_selection"]
e = "move_line_up"
h = "move_char_left"
i = "move_char_right"
j = "move_next_word_end"
k = "search_next"
l = "insert_mode"
n = "move_line_down"
o = "open_below"
pagedown = ["half_page_down", "goto_window_center"]
pageup = ["half_page_up", "goto_window_center"]

[keys.normal.Z]
e = "scroll_up"
n = "scroll_down"

[keys.normal.g]
a = "code_action"
h = "hover"

[keys.normal.space.w]
e = "jump_view_down"
i = "jump_view_up"
n = "jump_view_left"
o = "jump_view_right"

[keys.normal.z]
e = "scroll_up"
n = "scroll_down"

[keys.select]
G = "goto_last_line"
J = "move_next_long_word_end"
K = "search_prev"
L = "insert_at_line_start"
O = "open_above"
e = "move_line_up"
h = "move_char_left"
i = "move_char_right"
j = "move_next_word_end"
k = "search_next"
l = "insert_mode"
n = "move_line_down"
o = "open_below"

