#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/map.sh"

REPO_DIR="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
EXPORT_DIR="$REPO_DIR/artifacts"

patch_config_fish() {
  local dest="$1"
  # Strip nix store binary paths
  sed -i '' 's|/nix/store/[^/]*/bin/||g' "$dest"
  # Strip hm-session-vars source line
  sed -i '' '/hm-session-vars/d' "$dest"
  # Strip header
  sed -i '' '/DO NOT EDIT/d' "$dest"
  sed -i '' '/automatically by home-manager/d' "$dest"
  sed -i '' '/Only execute this file once per shell/d' "$dest"
  sed -i '' '/__fish_home_manager_config_sourced/d' "$dest"
  # Strip darwin-rebuild alias
  sed -i '' '/darwin-rebuild/d' "$dest"
  # Strip completions block
  sed -i '' '/add completions generated by Home Manager/,/^    end$/d' "$dest"
  # New lines go away
  sed -i '' '/^[[:space:]]*$/d' "$dest"
}

patch_emacs_init_el() {
  local dest="$1"
  sed -i '' 's|/etc/profiles/per-user/[^/]*/bin|/opt/homebrew/bin|g' "$dest"
  awk '
    /^\(use-package straight/ { found=1 }
    found && /^\(use-package general/ {
      print "(use-package straight"
      print "  :custom"
      print "  (straight-use-package-by-default t)"
      print "  (straight-current-profile '\''base)"
      print "  (straight-vc-git-default-protocol '\''ssh))"
      print ""
      found=0
    }
    !found { print }
  ' "$dest" > "$dest.tmp" && mv "$dest.tmp" "$dest"
}

mkdir -p "$EXPORT_DIR"
for pattern in "${ARTIFACT_SOURCES[@]}"; do
  for src in $HOME/$pattern; do
    [ -f "$src" ] || continue
    relative="${src#"$HOME"/}"
    dest="$EXPORT_DIR/$relative"
    mkdir -p "$(dirname "$dest")"
    rsync -aL "$src" "$dest"
    chmod 644 "$dest"
    if [[ "$dest" == *"/config.fish" ]]; then
      patch_config_fish "$dest"
    fi
    if [[ "$dest" == *"/init.el" ]]; then
      patch_emacs_init_el "$dest"
    fi
    echo "Exported: $relative"
  done
done
